# Generated by Django 4.1.6 on 2023-02-05 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedmain',
            name='messsage',
        ),
    ]
