# Generated by Django 4.1.6 on 2023-02-06 06:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_feedmain_messsage'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedmain',
            name='message',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
